# conda env create -f environment.yml
name: spatial
channels:
    - conda-forge
dependencies:
    - python=3.7
    - pip
    - jupyter
    - geopandas
    - pandas
    - matplotlib==3.3.2
    - descartes
    - folium
    - mplleaflet
    - plotly
    - RISE
    - pip:
        - world_bank_data
        - osmxtract
        
